spring:
  application:
    name: ongi

  profiles:
    default: prod

  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method