spring:
  application:
    name: ongi

  profiles:
    default: dev

  jackson:
    serialization:
      write-dates-as-timestamps: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
